Neos:
  Form:
    FusionRenderer:
      fusionPathPatterns:
        Neos.Fusion:Private/Fusion: true
        Neos.Form.FusionRenderer:Private/Fusion/Core: true
        Neos.Form.FusionRenderer:Private/Fusion/ContainerElements: true
        Neos.Form.FusionRenderer:Private/Fusion/Elements: true

    presets:
      'fusion':
        title: 'Fusion based Form Elements'
        parentPreset: 'default'
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              templatePathPattern: ~
              partialPathPattern: ~
              layoutPathPattern: ~
          'Neos.Form:Form':
            rendererClassName: 'Neos\Form\FusionRenderer\FusionFormRenderer'

  Neos:
    fusion:
      autoInclude:
        'Neos.Form.FusionRenderer': true

  Fusion:
    defaultContext:
      'Neos.Form': 'Neos\Form\FusionRenderer\Eel\Helper\FormHelper'
